### PR TITLE
Upgrade to 1.1.15

### PR DESCRIPTION
**Pull request by ericgaspar**
- *Upgrade to upstream version 1.1.15*
-  *Fix some linter warnings*

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
The test is stuck trying to create a backup after a restart of the LXC ... I believe that's because of https://github.com/YunoHost-Apps/borg_ynh/issues/60#issuecomment-745737178 ... we should remove that WantedBy multi-user target thing, otherwise that means "run the backup upon restart" ...

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by zamentur — APPROVED** [review]
LGTM

**Pull request merged**
